plugins {
    id 'com.android.application'
}

android {
    namespace 'ywdemo.example.yaoxiaowen'
    compileSdk 29

    defaultConfig {
        applicationId "ywdemo.example.yaoxiaowen"
        minSdk 24
        targetSdk 29
        versionCode 1
        versionName "1.0"

        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
        vectorDrawables {
            useSupportLibrary true
        }

        multiDexEnabled true

        // 仅支持 armeabi-v7a 架构
        ndk {
            abiFilters "armeabi-v7a"
        }
    }

    viewBinding {
        enable = true
    }

    buildTypes {
        debug {
            jniDebuggable true
        }
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }

    packagingOptions {
        resources {
            excludes += '/META-INF/{AL2.0,LGPL2.1}'
            excludes += 'META-INF/annotations/**'
            excludes += '**/annotations/**'
        }
        // 排除 arm64-v8a 架构，仅保留 armeabi-v7a
        exclude 'lib/arm64-v8a/**'
        pickFirst 'lib/armeabi-v7a/libc++_shared.so'
    }
}

dependencies {
    implementation 'androidx.core:core:1.3.2'
    implementation 'androidx.lifecycle:lifecycle-runtime:2.2.0'
    implementation 'androidx.appcompat:appcompat:1.2.0'
    implementation 'com.google.android.material:material:1.2.1'
    implementation 'androidx.constraintlayout:constraintlayout:2.0.4'
    testImplementation 'junit:junit:4.13.2'
    androidTestImplementation 'androidx.test.ext:junit:1.1.2'
    androidTestImplementation 'androidx.test.espresso:espresso-core:3.3.0'

    implementation 'com.tencent:mmkv-static:1.2.16'

    // 百度人脸SDK相关
    api files('libs/orbbec_module-debug.aar')
    api fileTree(include: ['*.jar'], dir: 'libs')
    api files('libs/ImiSDK.aar')
    api files('libs/deptrumSDK.aar')
    api files('libs/opencv.aar')
    api files('libs/FaceSDK_8.5_20241205-release.aar')
}
